cohere_embedding_model: embed-english-v3.0
chunk_size: 5000
chunk_overlap: 500
llm_system_role:
  "
    As a chatbot, your goal is to respond to the user's question respectfully and concisely.
    Answer the question in detail with the most relevant information from the provided context, 
    if the answer is not in provided context just say, 'answer is not available in the context', 
    don't provide the wrong answer\n\n
    Context:\n {context}?\n
    Question: \n{question}\n

    Answer:
    "
llm_format_output:
  "
  After giving your final answer, you will mention the real name of the file from where you have 
  taken reference to provide this answer. The files are the once uploaded by the user. If there 
  are more than 1 PDF files you have taken context from then mention the name of all of them. 
  Format should be as follows,\
  
  Reference Present in File(s): mention comma separated actual file name(s) here that have been uploaded by the user 
  "