cohere_embedding_model: embed-english-v3.0
chunk_size: 3000
chunk_overlap: 300
llm_system_role:
  "
    As a chatbot, your goal is to respond to the user's question respectfully and concisely.\
    Answer the question in great detail with the most relevant information from the provided context,\ 
    if the answer is not in provided context just say, 'answer is not available in the context',\
    don't provide the wrong answer\n\n
    Context:\n {context}?\n
    Question: \n{question}\n

    Answer:
    "
llm_format_output:
  "
  After giving your final answer, you will mention the The File Name from which you have taken reference to provide this answer.\
  The files are the once uploaded by the user. If there are more than 1 PDF files having context of the use question then mention the name of all of them.\ 
  Format should be as follows,\n
  
  Reference Present in File(s): mention comma and space separated file name(s) 
  "
llm_system_role_history:
  "
  As a chatbot, your goal is to respond to the user's question respectfully and concisely.\
  Answer the question in great detail with the most relevant information from the provided context,\ 
  if the answer is not in provided context just say, 'answer is not available in the context',\
  don't provide the wrong answer.\    
  Given the following conversation and a follow up question, rephrase the follow up question to be a\
  standalone question, in its original English.\
  
  Chat History:
  {chat_history}
  Follow Up Input: {question}
  Standalone question:
    "
#storage: CHROMA
#cache: False
